package pl.edu.pw.okno;


import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Toolbar;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import pl.edu.pw.okno.auth.AuthImpl;
import pl.edu.pw.okno.auth.BasicAuth;
import pl.edu.pw.okno.page.LoginPage;
import pl.edu.pw.okno.page.Menu;
import pl.edu.pw.okno.page.Properties;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class OKNO {

    public static final String APP_NAME = "OKNO";
    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        AuthImpl.getInstance().setMethod(new BasicAuth());
        Dialog.setDefaultBlurBackgroundRadius(8.0f);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Properties.getInstance().setUrl("http://176.119.57.214:5555");
        LoginPage.getInstance().show();
        Menu.setSideMenu();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
